[package]
name = "mohamedharbyii/ATP_GYM" # غير ده باسم اليوزر واسم البروجكت
version = "0.1.0"
description = "My Laravel API on Wasmer"
license = "MIT"

[dependencies]
"php/php" = "8.2" # نسخة الـ PHP اللي مشروعك شغال بيها

[fs]
"/app" = "." # بيعمل Map لملفات المشروع جوه الفولدر /app

[[command]]
name = "run"
module = "php/php:web"
runner = "https://webc.org/runner/wasi"
annotations = { wagi = { env = { DOCUMENT_ROOT = "/app/public" } } }